### ISSUE TITLE
[Request] thunderbird-beta

### ISSUE THREAD

**Issue by a61kt** [chaotic-aur/packages#1536]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/thunderbird-beta

### Utility this package has for you

Thunderbird Beta

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

I've already build binaries   for it
https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/thunderbird-beta

**Comment by Technetium1** [comment]
Build log: https://builds.garudalinux.org/repos/chaotic-aur/logs/thunderbird-beta.log
```
zstandard<=0.17.0,>=0.11.1: Installed with unexpected version "0.18.0"
Traceback (most recent call last):
File "/home/main-builder/pkgwork/src/thunderbird-100.0/./mach", line 96, in <module>
main(sys.argv[1:])
File "/home/main-builder/pkgwork/src/thunderbird-100.0/./mach", line 88, in main
mach = check_and_get_mach(os.path.dirname(os.path.realpath(__file__)))
File "/home/main-builder/pkgwork/src/thunderbird-100.0/./mach", line 35, in check_and_get_mach
return load_mach(dir_path, mach_path)
File "/home/main-builder/pkgwork/src/thunderbird-100.0/./mach", line 21, in load_mach
return mach_initialize.initialize(dir_path)
File "/home/main-builder/pkgwork/src/thunderbird-100.0/comm/build/mach_initialize.py", line 49, in initialize
driver = mach_init.initialize(topsrcdir)
File "/home/main-builder/pkgwork/src/thunderbird-100.0/build/mach_initialize.py", line 153, in initialize
_activate_python_environment(
File "/home/main-builder/pkgwork/src/thunderbird-100.0/build/mach_initialize.py", line 99, in _activate_python_environment
mach_environment.activate()
File "/home/main-builder/pkgwork/src/thunderbird-100.0/python/mach/mach/site.py", line 390, in activate
self.ensure()
File "/home/main-builder/pkgwork/src/thunderbird-100.0/python/mach/mach/site.py", line 368, in ensure
result = self._up_to_date()
File "/home/main-builder/pkgwork/src/thunderbird-100.0/python/mach/mach/site.py", line 353, in _up_to_date
_assert_pip_check(
File "/home/main-builder/pkgwork/src/thunderbird-100.0/python/mach/mach/site.py", line 1122, in _assert_pip_check
raise Exception(
Exception: The "mach" site is not compatible with the installed system Python packages.
==> ERROR: A failure occurred in build().
Aborting...
```

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/interfere/commit/aa6da33a50a90be192b80b27dcb518b2f1bf4a82

**Comment by Technetium1** [comment]
It failed again.

**Comment by dr460nf1r3** [comment]
Its failing during compilation now though:
```
TIER: configure pre-export export compile misc libs tools 0:59.87 1 error generated.
TIER: configure pre-export export compile misc libs tools 0:59.91 make[4]: *** [/home/main-builder/pkgwork/src/thunderbird-100.0/config/rules.mk:660: Unified_cpp_accessible_xul0.o] Error 1
TIER: configure pre-export export compile misc libs tools 0:59.91 make[3]: *** [/home/main-builder/pkgwork/src/thunderbird-100.0/config/recurse.mk:72: accessible/xul/target-objects] Error 2
TIER: configure pre-export export compile misc libs tools 0:59.91 make[3]: *** Waiting for unfinished jobs....
TIER: configure pre-export export compile misc libs tools 0:59.96 1 error generated.
TIER: configure pre-export export compile misc libs tools 1:00.01 make[4]: *** [/home/main-builder/pkgwork/src/thunderbird-100.0/config/rules.mk:660: Unified_cpp_accessible_html0.o] Error 1
TIER: configure pre-export export compile misc libs tools 1:00.01 make[3]: *** [/home/main-builder/pkgwork/src/thunderbird-100.0/config/recurse.mk:72: accessible/html/target-objects] Error 2
TIER: configure pre-export export compile misc libs tools 1:00.10 [0m[0m[1m[32m   Compiling[0m libc v0.2.112
TIER: configure pre-export export compile misc libs tools 1:00.69 1 error generated.
TIER: configure pre-export export compile misc libs tools 1:00.73 In file included from Unified_cpp_accessible_base0.cpp:119:
TIER: configure pre-export export compile misc libs tools 1:00.73 In file included from /home/main-builder/pkgwork/src/thunderbird-100.0/accessible/base/FocusManager.cpp:21:
TIER: configure pre-export export compile misc libs tools 1:00.73 In file included from /home/main-builder/pkgwork/src/thunderbird-100.0/obj/dist/include/mozilla/dom/BrowserParent.h:23:
TIER: configure pre-export export compile misc libs tools 1:00.73 In file included from /home/main-builder/pkgwork/src/thunderbird-100.0/obj/dist/include/mozilla/layout/RemoteLayerTreeOwner.h:17:
TIER: configure pre-export export compile misc libs tools 1:00.73 In file included from /home/main-builder/pkgwork/src/thunderbird-100.0/obj/dist/include/nsDisplayList.h:48:
TIER: configure pre-export export compile misc libs tools 1:00.73 In file included from /home/main-builder/pkgwork/src/thunderbird-100.0/obj/dist/include/nsCSSRenderingBorders.h:20:
TIER: configure pre-export export compile misc libs tools 1:00.73 In file included from /home/main-builder/pkgwork/src/thunderbird-100.0/obj/dist/include/gfxUtils.h:23:
TIER: configure pre-export export compile misc libs tools 1:00.73 In file included from /home/main-builder/pkgwork/src/thunderbird-100.0/obj/dist/include/mozilla/webrender/WebRenderTypes.h:11:
TIER: configure pre-export export compile misc libs tools 1:00.73 In file included from /home/main-builder/pkgwork/src/thunderbird-100.0/obj/dist/include/mozilla/webrender/webrender_ffi.h:103:
TIER: configure pre-export export compile misc libs tools 1:00.73 [1m/home/main-builder/pkgwork/src/thunderbird-100.0/obj/dist/include/mozilla/webrender/webrender_ffi_generated.h:24:33: [0m[0;1;31merror: [0m[1mredefinition of 'ROOT_CLIP_CHAIN'[0m
TIER: configure pre-export export compile misc libs tools 1:00.73 constexpr static const uint64_t ROOT_CLIP_CHAIN = ~0;
TIER: configure pre-export export compile misc libs tools 1:00.74 [0;1;32m                                ^
TIER: configure pre-export export compile misc libs tools 1:00.74 [0m[1m/home/main-builder/pkgwork/src/thunderbird-100.0/obj/dist/include/mozilla/webrender/webrender_ffi.h:75:16: [0m[0;1;30mnote: [0mprevious definition is here[0m
TIER: configure pre-export export compile misc libs tools 1:00.74 const uint64_t ROOT_CLIP_CHAIN = ~0;
TIER: configure pre-export export compile misc libs tools 1:00.74 [0;1;32m               ^
TIER: configure pre-export export compile misc libs tools 1:00.76 [0mmake[4]: *** [/home/main-builder/pkgwork/src/thunderbird-100.0/config/rules.mk:660: Unified_cpp_accessible_ipc0.o] Error 1
TIER: configure pre-export export compile misc libs tools 1:00.76 make[3]: *** [/home/main-builder/pkgwork/src/thunderbird-100.0/config/recurse.mk:72: accessible/ipc/target-objects] Error 2
TIER: configure pre-export export compile misc libs tools 1:02.16 [0m[0m[1m[32m   Compiling[0m cfg-if v1.0.0
TIER: configure pre-export export compile misc libs tools 1:02.31 [0m[0m[1m[32m   Compiling[0m autocfg v1.0.1 (/home/main-builder/pkgwork/src/thunderbird-100.0/third_party/rust/autocfg)
TIER: configure pre-export export compile misc libs tools 1:02.99 1 error generated.
TIER: configure pre-export export compile misc libs tools 1:03.05 make[4]: *** [/home/main-builder/pkgwork/src/thunderbird-100.0/config/rules.mk:660: Unified_cpp_accessible_generic0.o] Error 1
TIER: configure pre-export export compile misc libs tools 1:03.05 make[3]: *** [/home/main-builder/pkgwork/src/thunderbird-100.0/config/recurse.mk:72: accessible/generic/target-objects] Error 2
TIER: configure pre-export export compile misc libs tools 1:03.31 1 error generated.
TIER: configure pre-export export compile misc libs tools 1:03.37 make[4]: *** [/home/main-builder/pkgwork/src/thunderbird-100.0/config/rules.mk:660: Unified_cpp_accessible_base1.o] Error 1
TIER: configure pre-export export compile misc libs tools 1:03.37 make[4]: *** Waiting for unfinished jobs....
TIER: configure pre-export export compile misc libs tools 1:03.48 1 error generated.
TIER: configure pre-export export compile misc libs tools 1:03.53 make[4]: *** [/home/main-builder/pkgwork/src/thunderbird-100.0/config/rules.mk:660: Unified_cpp_accessible_base0.o] Error 1
TIER: configure pre-export export compile misc libs tools 1:03.53 make[3]: *** [/home/main-builder/pkgwork/src/thunderbird-100.0/config/recurse.mk:72: accessible/base/target-objects] Error 2
```

**Comment by a61kt** [comment]
@dr460nf1r3 @Technetium1 i hope it helps (it works for me)
https://build.opensuse.org/package/view_file/home:Area51Kacz:branches:home:ungoogled_chromium:testing/thunderbird-beta/psutil.patch?expand=1
https://build.opensuse.org/package/view_file/home:Area51Kacz:branches:home:ungoogled_chromium:testing/thunderbird-beta/PKGBUILD?expand=1

**Comment by yurikoles** [comment]
AUR maintainer here.

Recent versions doesn't longer fail to build.

**Comment by Technetium1** [comment]
:hot_face: 
```
real    53m4.752s
user    310m59.872s
sys     20m15.008s
```

**Comment by xiota** [comment]
@yurikoles I understand you had other priorities...  Let me know if you want to be added back as comaintainer.

**Comment by yurikoles** [comment]
@xiota 

Yes, that would be nice, thank you.
