### ISSUE TITLE
[Request] buttercup-desktop

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1737]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/buttercup-desktop

### Utility this package has for you

Javascript Password Vault - Multi-Platform Desktop Application

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by tio-trom** [comment]
Cannot find this in your repos anymore.

**Comment by dr460nf1r3** [comment]
```

ERROR in ./resources/icons/error.png
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at getHashDigest (/home/main-builder/pkgwork/src/buttercup-desktop-2.17.0/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /home/main-builder/pkgwork/src/buttercup-desktop-2.17.0/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/home/main-builder/pkgwork/src/buttercup-desktop-2.17.0/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/home/main-builder/pkgwork/src/buttercup-desktop-2.17.0/node_modules/file-loader/dist/index.js:29:48)
 @ ./source/renderer/library/icons.ts 9:19-72
 @ ./source/renderer/components/AddVaultMenu.tsx 55:16-43
 @ ./source/renderer/App.tsx 38:23-59
 @ ./source/renderer/index.tsx 30:14-30
```

**Comment by xiota** [comment]
Last build 2023-05-12.

**Comment by xiota** [comment]
EOL Electron/22.3.27.  Metrics 14.
