### ISSUE TITLE
[Outdated] mutter-performance

### ISSUE THREAD

**Issue by Inetol** [chaotic-aur/packages#2070]
### If available, link to the latest build

[mutter-performance.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/mutter-performance.log)

### Package name

`mutter-performance`

### Latest build

`42.5-1.2`

### Latest version available

`43.0+r97+gd313c8f4f-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

There seems to be "some" errors when building the package to version 43.

**Comment by Technetium1** [comment]
We must skip testing as it's not adapted to compile on systems without a display / Wayland. These _should_ be 'expected failures'.

```
Running test case...
libmutter-Message: 08:52:12.795: Running Mutter (using mutter 43.0) as a Wayland display server
libmutter-Message: 08:52:12.862: Created surfaceless renderer without GPU
libmutter-Message: 08:52:12.888: Disabling DMA buffer screen sharing (not hardware accelerated)
libmutter-Message: 08:52:12.888: Disabling DMA buffer screen sharing (implicit modifiers not supported)
libmutter-Message: 08:52:12.888: Added virtual monitor Meta-0
libmutter-Message: 08:52:12.891: Using public X11 display :0, (using :1 for managed services)
libmutter-Message: 08:52:12.891: Using Wayland display name 'get-state-gdbus'
Window manager warning: Failed to set environment variable GNOME_SETUP_DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable XAUTHORITY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable WAYLAND_DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Failed to initialize glamor, falling back to sw

(mutter:19931): libmutter-WARNING **: 08:52:12.916: Failed to create colord device for 'xrandr-MetaVendor-MetaVirtualMonitor-0x00': Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.10/site-packages/dbusmock/mockobject.py", line 161, in wrapper
    return func(*[self_arg, *args], **kwargs)
  File "<string>", line 72, in CreateDevice
  File "/usr/lib/python3.10/site-packages/dbusmock/mockobject.py", line 345, in AddObject
    obj = DBusMockObject(self.bus_name,
  File "/usr/lib/python3.10/site-packages/dbusmock/mockobject.py", line 198, in __init__
    dbus.service.Object.__init__(self, bus_name, path)
  File "/usr/lib/python3.10/site-packages/dbus/service.py", line 463, in __init__
    validate_object_path(object_path)
ValueError: Invalid object path '/org/freedesktop/ColorManager/devices/xrandr_MetaVendor_MetaVirtualMonitor_0x00_main-builder_1000': contains invalid character '-'

(EE) could not connect to wayland server
Traceback (most recent call last):
  File "/home/main-builder/pkgwork/src/mutter-performance/tools/get-state.py", line 230, in <module>
    monitor_config.print_current_state(short=args.short)
  File "/home/main-builder/pkgwork/src/mutter-performance/tools/get-state.py", line 83, in print_current_state
    variant = self.get_current_state()
  File "/home/main-builder/pkgwork/src/mutter-performance/tools/get-state.py", line 194, in get_current_state
    result = subprocess.run(command, shell=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'gdbus call -e -d org.gnome.Mutter.DisplayConfig -o /org/gnome/Mutter/DisplayConfig -m org.gnome.Mutter.DisplayConfig.GetCurrentState' returned non-zero exit status 1.
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――


Summary of Failures:

144/216 mutter:clutter+clutter/conform / actor-layout                                                  FAIL             4.12s   (exit status 251 or signal 123 SIGinvalid)
146/216 mutter:clutter+clutter/conform / actor-offscreen-redirect                                      FAIL             1.82s   (exit status 251 or signal 123 SIGinvalid)
155/216 mutter:clutter+clutter/conform / frame-clock                                                   FAIL             1.56s   (exit status 251 or signal 123 SIGinvalid)
156/216 mutter:clutter+clutter/conform / frame-clock-timeline                                          FAIL             1.43s   (exit status 251 or signal 123 SIGinvalid)
157/216 mutter:clutter+clutter/conform / grab                                                          FAIL             1.62s   (exit status 251 or signal 123 SIGinvalid)
160/216 mutter:clutter+clutter/conform / timeline                                                      FAIL             1.98s   (exit status 251 or signal 123 SIGinvalid)
161/216 mutter:clutter+clutter/conform / timeline-interpolate                                          FAIL             4.84s   (exit status 251 or signal 123 SIGinvalid)
163/216 mutter:clutter+clutter/conform / timeline-rewind                                               FAIL             1.98s   (exit status 251 or signal 123 SIGinvalid)
165/216 mutter:core+mutter/unit / unit                                                                 FAIL             1.57s   (exit status 251 or signal 123 SIGinvalid)
166/216 mutter:core+mutter/backend / monitor-unit                                                      FAIL             1.76s   (exit status 251 or signal 123 SIGinvalid)
169/216 mutter:core+mutter/compositor / stage-views                                                    FAIL             1.93s   (exit status 251 or signal 123 SIGinvalid)
172/216 mutter:core+mutter/unit / color-management                                                     FAIL             2.15s   (exit status 251 or signal 123 SIGinvalid)
175/216 mutter:core+mutter/backends/native / native-unit                                               FAIL             1.51s   (exit status 251 or signal 123 SIGinvalid)
176/216 mutter:core+mutter/backends/native / pointer-constraints                                       FAIL             1.51s   (exit status 251 or signal 123 SIGinvalid)
177/216 mutter:core+mutter/backends/native / ref-test-sanity                                           FAIL             1.49s   (exit status 251 or signal 123 SIGinvalid)
179/216 mutter:core+mutter/wayland / wayland-unit                                                      FAIL             1.52s   (exit status 251 or signal 123 SIGinvalid)
181/216 mutter:core+mutter/wayland / wayland-fullscreen                                                FAIL             1.45s   (exit status 251 or signal 123 SIGinvalid)
182/216 mutter:core+mutter/stacking / basic-x11                                                        FAIL             1.45s   (exit status 251 or signal 123 SIGinvalid)
183/216 mutter:core+mutter/stacking / basic-wayland                                                    FAIL             1.46s   (exit status 251 or signal 123 SIGinvalid)
184/216 mutter:core+mutter/stacking / client-side-decorated                                            FAIL             1.43s   (exit status 251 or signal 123 SIGinvalid)
185/216 mutter:core+mutter/stacking / closed-transient                                                 FAIL             1.45s   (exit status 251 or signal 123 SIGinvalid)
186/216 mutter:core+mutter/stacking / closed-transient-no-default-focus                                FAIL             1.55s   (exit status 251 or signal 123 SIGinvalid)
187/216 mutter:core+mutter/stacking / closed-transient-no-input-no-take-focus-parent                   FAIL             1.91s   (exit status 251 or signal 123 SIGinvalid)
188/216 mutter:core+mutter/stacking / closed-transient-no-input-no-take-focus-parents                  FAIL             1.48s   (exit status 251 or signal 123 SIGinvalid)
189/216 mutter:core+mutter/stacking / closed-transient-no-input-parent                                 FAIL             1.62s   (exit status 251 or signal 123 SIGinvalid)
190/216 mutter:core+mutter/stacking / closed-transient-no-input-parent-delayed-focus-default-cancelled FAIL             2.49s   (exit status 251 or signal 123 SIGinvalid)
191/216 mutter:core+mutter/stacking / closed-transient-no-input-parents                                FAIL             3.74s   (exit status 251 or signal 123 SIGinvalid)
192/216 mutter:core+mutter/stacking / closed-transient-no-input-parents-queued-default-focus-destroyed FAIL             1.80s   (exit status 251 or signal 123 SIGinvalid)
193/216 mutter:core+mutter/stacking / closed-transient-only-take-focus-parents                         FAIL             1.50s   (exit status 251 or signal 123 SIGinvalid)
194/216 mutter:core+mutter/stacking / minimized                                                        FAIL             1.67s   (exit status 251 or signal 123 SIGinvalid)
195/216 mutter:core+mutter/stacking / mixed-windows                                                    FAIL             1.54s   (exit status 251 or signal 123 SIGinvalid)
196/216 mutter:core+mutter/stacking / set-parent                                                       FAIL             1.51s   (exit status 251 or signal 123 SIGinvalid)
197/216 mutter:core+mutter/stacking / override-redirect                                                FAIL             1.70s   (exit status 251 or signal 123 SIGinvalid)
198/216 mutter:core+mutter/stacking / set-override-redirect-parent                                     FAIL             1.44s   (exit status 251 or signal 123 SIGinvalid)
199/216 mutter:core+mutter/stacking / set-parent-exported                                              FAIL             1.61s   (exit status 251 or signal 123 SIGinvalid)
200/216 mutter:core+mutter/stacking / restore-size                                                     FAIL             1.82s   (exit status 251 or signal 123 SIGinvalid)
201/216 mutter:core+mutter/stacking / unmaximize-new-size                                              FAIL             1.51s   (exit status 251 or signal 123 SIGinvalid)
202/216 mutter:core+mutter/stacking / fullscreen-maximize                                              FAIL             1.48s   (exit status 251 or signal 123 SIGinvalid)
203/216 mutter:core+mutter/stacking / unfullscreen-strut-change                                        FAIL             1.47s   (exit status 251 or signal 123 SIGinvalid)
204/216 mutter:core+mutter/stacking / restore-position                                                 FAIL             1.54s   (exit status 251 or signal 123 SIGinvalid)
205/216 mutter:core+mutter/stacking / default-size                                                     FAIL             1.65s   (exit status 251 or signal 123 SIGinvalid)
206/216 mutter:core+mutter/stacking / modals                                                           FAIL             1.81s   (exit status 251 or signal 123 SIGinvalid)
207/216 mutter:core+mutter/stacking / map-fixed-size                                                   FAIL             1.52s   (exit status 251 or signal 123 SIGinvalid)
208/216 mutter:core+mutter/stacking / client-resize-respect-constraints                                FAIL             2.01s   (exit status 251 or signal 123 SIGinvalid)
209/216 mutter:core+mutter/stacking / map-on-hotplug                                                   FAIL             2.70s   (exit status 251 or signal 123 SIGinvalid)
210/216 mutter:core+mutter/stacking / workspace-basic                                                  FAIL             2.06s   (exit status 251 or signal 123 SIGinvalid)
211/216 mutter:core+mutter/stacking / workspace-test                                                   FAIL             1.49s   (exit status 251 or signal 123 SIGinvalid)
212/216 mutter:core+mutter/stacking / always-on-top                                                    FAIL             1.69s   (exit status 251 or signal 123 SIGinvalid)
213/216 mutter:core+mutter/stacking / focus-default-window-globally-active-input                       FAIL             2.36s   (exit status 251 or signal 123 SIGinvalid)
214/216 mutter:core+mutter/x11 / x11                                                                   FAIL            12.16s   (exit status 133 or signal 5 SIGTRAP)
215/216 mutter:tools / get-state-tool-gio                                                              FAIL             1.54s   (exit status 251 or signal 123 SIGinvalid)
216/216 mutter:tools / get-state-tool-gdbus                                                            FAIL             1.53s   (exit status 251 or signal 123 SIGinvalid)

Ok:                 156 
Expected Fail:      8   
Fail:               52  
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
```

**Comment by Technetium1** [comment]
`Finished making: mutter-performance 43.0+r97+gd313c8f4f-1 (Fri 04 Nov 2022 03:45:11 PM CET)`
