### ISSUE TITLE
[Remove] nody-greeter

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2829]
### Package:

https://aur.archlinux.org/packages/nody-greeter

### Purpose:

LightDM greeter that allows to create wonderful themes with web technologies. Made in Node.js

### Benefits:

LightDM webkit2-greeter is not longer maintained and the latest update of webkit-gtk broke it. nody-greeter allows to create or use themes that are based on similar approach of webkit2 allowing users to set interactive themes in LightDM.

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
```
Installing packages with 'npm ci --production -s'
Error: Command failed: npm ci --production -s
    at checkExecSyncError (node:child_process:861:11)
    at Object.execSync (node:child_process:932:15)
    at create_build (/home/main-builder/pkgwork/src/nody-greeter-1.5.2/build.js:156:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async build (/home/main-builder/pkgwork/src/nody-greeter-1.5.2/build.js:366:3) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2560,
  stdout: null,
  stderr: null
}
```
But it still succeeded, please confirm it's fine @D3vil0p3r

**Comment by D3vil0p3r** [comment]
When I compiled it and used on some LightDM themes, it worked. I dont remember to have received that message. I should check again.

**Comment by xiota** [comment]
Dropping this package because it's failing to build and maintainer MIA.  Package never updated since submission, and comment from Oct 2023 was ignored.

**Comment by D3vil0p3r** [comment]
@xiota I had open requests on it: https://github.com/JezerM/nody-greeter/issues/50#event-13498788278
https://aur.archlinux.org/packages/nody-greeter
but if you pinged me here, I could push more upstream. I forgot to keep labelled this issue ticket as opened.

I just submitted an orphan request on the AUR package.

**Comment by xiota** [comment]
Reopened issue to make easier to track.  When/if package ia fixed, can be added back.

**Comment by xiota** [comment]
This package returned with transition to v4 builder.  However, it uses EOL Electron/27.3.11, so may be dropped again "soon".  Metrics 14.
