### ISSUE TITLE
[Rebuild] Vorta

### ISSUE THREAD

**Issue by erenfro** [chaotic-aur/packages#2900]
### Packages:

https://aur.archlinux.org/pkgbase/vorta

### Latest chaotic version

0.8.12-1.3

### Reason for rebuild

Broken and runtime dumps this:
Requirement.parse('platformdirs<4.0.0,>=2.6.0'), {'vorta'})
pkg_resources.DistributionNotFound: The 'platformdirs<4.0.0,>=2.6.0' distribution was not found and is required by vorta

### Logs

<details><summary>...</summary>

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 631, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (platformdirs 4.0.0 (/usr/lib/python3.11/site-packages), Requirement.parse('platformdirs<4.0.0,>=2.6.0'), {'vorta'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/vorta", line 33, in <module>
    sys.exit(load_entry_point('vorta==0.8.12', 'gui_scripts', 'vorta')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/vorta", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/vorta/__main__.py", line 9, in <module>
    from vorta.store.connection import init_db
  File "/usr/lib/python3.11/site-packages/vorta/store/connection.py", line 6, in <module>
    from .migrations import run_migrations
  File "/usr/lib/python3.11/site-packages/vorta/store/migrations.py", line 4, in <module>
    from .models import (
  File "/usr/lib/python3.11/site-packages/vorta/store/models.py", line 11, in <module>
    from vorta.utils import slugify
  File "/usr/lib/python3.11/site-packages/vorta/utils.py", line 18, in <module>
    from vorta.borg._compatibility import BorgCompatibility
  File "/usr/lib/python3.11/site-packages/vorta/borg/_compatibility.py", line 1, in <module>
    from pkg_resources import parse_version
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3327, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 633, in _build_master
    return cls._build_from_requirements(__requires__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 646, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'platformdirs<4.0.0,>=2.6.0' distribution was not found and is required by vorta
```
</details>

### Builds?

It builds, but even on my own aurto server it's failing to run with the same stack traces.

### More information

Looking further into the root cause upstream and will be in contact with the original AUR maintainer as well on findings that possibly result in corrections.

**Comment by erenfro** [comment]
At first, it's looking like a problem with python-platformdirs itself simply being "too new" being at 4.0.0

**Comment by xiota** [comment]
> It builds, but even on my own aurto server it's failing to run with the same stack traces.

Rebuild will not fix this unless pkgbuild is modified.  Appears to be an upstream issue.  The release was about 7 months ago, so probably already fixed.  Did you try building and running [`vorta-git`](https://aur.archlinux.org/packages/vorta-git)?

Vorta will run if you delete `/usr/lib/python3.11/site-packages/vorta-0.8.12-py3.11.egg-info/requires.txt`.

**Comment by xiota** [comment]
Someone commented on the aur page that the requirement has been removed from the upstream project.

I made a one-time build with the requirements file deleted so that the program can be used while waiting for the next release.  If the problem recurs, feel free to leave a comment.
