### ISSUE TITLE
[Request] python-materialyoucolor-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3077]
### Package:

https://aur.archlinux.org/packages/python-materialyoucolor-git

### Purpose:

Python generaton algorithms in Python for material you color. Useful for Linux theming (i.e. Hyprland)

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by D3vil0p3r** [comment]
@xiota can you give a look to it?

**Comment by xiota** [comment]
I took a look at the pkgbuild and git repo, but haven't tried building yet.

What other programs/packages use this?  Is the test/demo script installed by the package?

**Comment by D3vil0p3r** [comment]
It is used as dependency for https://github.com/end-4/dots-hyprland

**Comment by Technetium1** [comment]
missing setuptools dep:
```
==> Starting build()...
* Getting build dependencies for wheel...

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _b
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'

ERROR Backend 'setuptools.build_meta:__legacy__' is not available.
==> ERROR: A failure occurred in build().
```

**Comment by D3vil0p3r** [comment]
@Technetium1 fixed upstream, can you check please?

**Comment by Technetium1** [comment]
@D3vil0p3r Thanks for checking up on this, all is well now. `Finished making: python-materialyoucolor-git 2.0.9.r1.g57ec2e4-1 (Fri 05 Apr 2024 07:47:38 PM CEST)`
