### ISSUE TITLE
[Rebuild]  mtkclient-git

### ISSUE THREAD

**Issue by real-LiHua** [chaotic-aur/packages#3175]
### Packages:

https://aur.archlinux.org/packages/mtkclient-git

### Latest chaotic version
1.63.r123.g0b0067e-1

### Reason for rebuild

Upstream fixed mtk, mtk_gui and stage2 triggering ModuleNotFoundError exception due to incorrect pyproject.toml configuration.

```bash
$ mtk --help
Traceback (most recent call last):
  File "/usr/bin/mtk", line 5, in <module>
    from mtk import main
ModuleNotFoundError: No module named 'mtk'
```
```bash
$ mtk_gui   
Traceback (most recent call last):
  File "/usr/bin/mtk_gui", line 5, in <module>
    from mtk_gui import main
ModuleNotFoundError: No module named 'mtk_gui'
```
```bash
$ stage2 --help
Traceback (most recent call last):
  File "/usr/bin/stage2", line 5, in <module>
    from stage2 import main
ModuleNotFoundError: No module named 'stage2'
```

https://github.com/bkerler/mtkclient/pull/1021

**Comment by xiota** [comment]
`-git` packages automatically rebuild.  Most within a few hours.  Some within a couple days.
```
$ pacman -Si mtkclient-git | grep Date
Build Date      : Tue 28 May 2024 04:49:28 PM UTC
```
