### ISSUE TITLE
[Bug] `river-git-0.3.5.r31.g1b5dd21-1` crashes on launch

### ISSUE THREAD

**Issue by 0nobody0** [chaotic-aur/packages#3370]
### Packages:

https://aur.archlinux.org/packages/river-git

### Latest chaotic version

`0.3.5.r31.g1b5dd21-1`

### What happens?

after upgrading to `river-git-0.3.5.r31.g1b5dd21-1`, `river` crashes on launch:
```
Oct 24 21:44:41 hostname kernel: traps: river[723] trap invalid opcode ip:10362f0 sp:7ffe8fc11908 error:0 in river[352f0,102b000+8b000]
Oct 24 21:44:41 hostname systemd-coredump[724]: Process 723 (river) of user 1000 terminated abnormally with signal 4/ILL, processing...
Oct 24 21:44:41 hostname systemd-coredump[725]: Process 723 (river) of user 1000 dumped core.
                                                    Module river without build-id.
                                                    #0  0x00000000010362f0 compiler_rt.memcpy.memcpy (river + 0x362f0)
```
going back to river-git-0.3.5.r28.g26f599b-1 everything works fine again. tried a debug build of the latest git source and it runs fine as well.

### What is expected to happen?

posted this crash as an [issue](https://codeberg.org/river/river/issues/1156) on the `river` codeberg page and it was mentioned that this may be related to the AUR package not being passed `-Dcpu=baseline`?

### More information

stack trace:
```
            PID: 743 (river)
           UID: 1000 (username)
           GID: 1000 (username)
        Signal: 4 (ILL)
     Timestamp: Thu 2024-10-24 18:50:33 CDT (10min ago)
  Command Line: river
    Executable: /usr/bin/river
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (username)
       Boot ID: dddb28f2c6a34331995199a367fa8a6a
    Machine ID: 0819fbb25f964772b60181f487389b69
      Hostname: hostname
       Storage: /var/lib/systemd/coredump/core.river.1000.dddb28f2c6a34331995199a367fa8a6a.743.1729813833000000.zst (present)
  Size on Disk: 1M
       Message: Process 743 (river) of user 1000 dumped core.
                
                Module river without build-id.
                Stack trace of thread 743:
                #0  0x00000000010362f0 compiler_rt.memcpy.memcpy (river + 0x362f0)
                #1  0x00007a5821eca494 n/a (libLLVM.so.18.1 + 0x4eca494)
                #2  0x00007a581d5f1b41 n/a (libLLVM.so.18.1 + 0x5f1b41)
                #3  0x00007a58286155b7 n/a (ld-linux-x86-64.so.2 + 0x45b7)
                #4  0x00007a58286156ad n/a (ld-linux-x86-64.so.2 + 0x46ad)
                #5  0x00007a582862de20 n/a (ld-linux-x86-64.so.2 + 0x1ce20)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 15.2
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/river...
[New LWP 743]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
[?2004hEnable debuginfod for this session? (y or [n]) y
[?2004l
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `river'.
Program terminated with signal SIGILL, Illegal instruction.
#0  compiler_rt.memcpy.memcpy (dest=0x7a58250b13d0 <llvm::sampleprof::ExtBinaryHdrLayoutTable+16> "\001", src=0x7a5824931220 <C.729.0> "\001", len=<optimized out>) at /usr/lib/zig/compiler_rt/memcpy.zig:19
[?2004h(gdb) thread apply all backtrace full
[?2004l
Thread 1 (Thread 0x7a581cf0a140 (LWP 743)):
#0  compiler_rt.memcpy.memcpy (dest=0x7a58250b13d0 <llvm::sampleprof::ExtBinaryHdrLayoutTable+16> "\001", src=0x7a5824931220 <C.729.0> "\001", len=<optimized out>) at /usr/lib/zig/compiler_rt/memcpy.zig:19
        d = 0x7a58250b13d0 <llvm::sampleprof::ExtBinaryHdrLayoutTable+16> "\001"
        s = 0x7a5824931220 <C.729.0> "\001"
        n = 279
        d = <optimized out>
        s = <optimized out>
        n = <optimized out>
#1  0x00007a5821eca494 in memcpy () at /usr/include/bits/string_fortified.h:29
No locals.
#2  llvm::SmallVectorTemplateBase<llvm::sampleprof::SecHdrTableEntry, true>::uninitialized_copy<llvm::sampleprof::SecHdrTableEntry const, llvm::sampleprof::SecHdrTableEntry> () at /usr/src/debug/llvm/llvm-18.1.8.src/include/llvm/ADT/SmallVector.h:533
No locals.
#3  llvm::SmallVectorTemplateBase<llvm::sampleprof::SecHdrTableEntry, true>::uninitialized_copy<llvm::sampleprof::SecHdrTableEntry const, llvm::sampleprof::SecHdrTableEntry> () at /usr/src/debug/llvm/llvm-18.1.8.src/include/llvm/ADT/SmallVector.h:524
No locals.
#4  llvm::SmallVectorImpl<llvm::sampleprof::SecHdrTableEntry>::append<llvm::sampleprof::SecHdrTableEntry const*, void> () at /usr/src/debug/llvm/llvm-18.1.8.src/include/llvm/ADT/SmallVector.h:700
No locals.
#5  0x00007a581d5f1b41 in llvm::SmallVectorImpl<llvm::sampleprof::SecHdrTableEntry>::append () at /usr/src/debug/llvm/llvm-18.1.8.src/include/llvm/ADT/SmallVector.h:712
No locals.
#6  llvm::SmallVector<llvm::sampleprof::SecHdrTableEntry, 8u>::SmallVector () at /usr/src/debug/llvm/llvm-18.1.8.src/include/llvm/ADT/SmallVector.h:1240
No locals.
#7  __static_initialization_and_destruction_0 () at /usr/src/debug/llvm/llvm-18.1.8.src/include/llvm/ProfileData/SampleProfWriter.h:255
No locals.
#8  _GLOBAL__sub_I_SampleProfWriter.cpp(void) () at /usr/src/debug/llvm/llvm-18.1.8.src/lib/ProfileData/SampleProfWriter.cpp:936
No locals.
#9  0x00007a58286155b7 in call_init (l=<optimized out>, argc=1, argv=0x7fff3dca6c48, env=0x7fff3dca6c58) at dl-init.c:74
        j = 0
        jm = <optimized out>
        addrs = <optimized out>
        init_array = <optimized out>
        __PRETTY_FUNCTION__ = "call_init"
        init_array = <optimized out>
        j = <optimized out>
        jm = <optimized out>
        addrs = <optimized out>
#10 call_init (l=<optimized out>, argc=1, argv=0x7fff3dca6c48, env=0x7fff3dca6c58) at dl-init.c:26
        init_array = <optimized out>
        __PRETTY_FUNCTION__ = "call_init"
        j = <optimized out>
        jm = <optimized out>
        addrs = <optimized out>
#11 0x00007a58286156ad in _dl_init (main_map=0x7a58286482e0, argc=1, argv=0x7fff3dca6c48, env=0x7fff3dca6c58) at dl-init.c:121
        preinit_array = <optimized out>
        preinit_array_size = <optimized out>
        i = <optimized out>
#12 0x00007a582862de20 in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
        TD_SLEEP = TD_SLEEP
        TD_CREATE = TD_CREATE
        _URC_FATAL_PHASE1_ERROR = _URC_FATAL_PHASE1_ERROR
        TD_CATCHSIG = TD_CATCHSIG
        cet_permissive = cet_permissive
        plt_rewrite_jmp = plt_rewrite_jmp
        TD_LOCK_TRY = TD_LOCK_TRY
        PREFERRED_FEATURE_INDEX_1 = PREFERRED_FEATURE_INDEX_1
        PREFERRED_FEATURE_INDEX_MAX = PREFERRED_FEATURE_INDEX_MAX
        arch_kind_unknown = arch_kind_unknown
        TD_SWITCHFROM = TD_SWITCHFROM
        cache_extension_tag_generator = cache_extension_tag_generator
        cache_extension_tag_glibc_hwcaps = cache_extension_tag_glibc_hwcaps
        _URC_INSTALL_CONTEXT = _URC_INSTALL_CONTEXT
        _bitindex_arch_Prefer_MAP_32BIT_EXEC = _bitindex_arch_Prefer_MAP_32BIT_EXEC
        TD_DEATH = TD_DEATH
        RT_CONSISTENT = RT_CONSISTENT
        LA_ACT_CONSISTENT = LA_ACT_CONSISTENT
        rtld_mode_verify = rtld_mode_verify
        TD_MAX_EVENT_NUM = TD_TIMEOUT
        RT_DELETE = RT_DELETE
        relocate_time = 42071206
        DL_LOOKUP_ADD_DEPENDENCY = DL_LOOKUP_ADD_DEPENDENCY
        TD_READY = TD_READY
        _bitindex_arch_Slow_SSE4_2 = _bitindex_arch_Slow_SSE4_2
        rtld_mode_help = rtld_mode_help
        cpuid_register_index_eax = cpuid_register_index_eax
        CPUID_INDEX_1 = CPUID_INDEX_1
        CPUID_INDEX_7 = CPUID_INDEX_7
        CPUID_INDEX_80000001 = CPUID_INDEX_80000001
        CPUID_INDEX_D_ECX_1 = CPUID_INDEX_D_ECX_1
        CPUID_INDEX_80000007 = CPUID_INDEX_80000007
        CPUID_INDEX_80000008 = CPUID_INDEX_80000008
        CPUID_INDEX_7_ECX_1 = CPUID_INDEX_7_ECX_1
        CPUID_INDEX_19 = CPUID_INDEX_19
        CPUID_INDEX_14_ECX_0 = CPUID_INDEX_14_ECX_0
        CPUID_INDEX_24_ECX_0 = CPUID_INDEX_24_ECX_0
        CPUID_INDEX_MAX = CPUID_INDEX_MAX
        dso_sort_algorithm_original = dso_sort_algorithm_original
        TD_CONCURRENCY = TD_CONCURRENCY
        lt_executable = lt_executable
        cpuid_register_index_ebx = cpuid_register_index_ebx
        _bitindex_arch_I686 = _bitindex_arch_I686
        cache_extension_count = cache_extension_count
        PTHREAD_MUTEX_TIMED_NP = PTHREAD_MUTEX_TIMED_NP
        PTHREAD_MUTEX_RECURSIVE_NP = PTHREAD_MUTEX_RECURSIVE_NP
        PTHREAD_MUTEX_ERRORCHECK_NP = PTHREAD_MUTEX_ERRORCHECK_NP
        PTHREAD_MUTEX_ADAPTIVE_NP = PTHREAD_MUTEX_ADAPTIVE_NP
        PTHREAD_MUTEX_NORMAL = PTHREAD_MUTEX_TIMED_NP
        PTHREAD_MUTEX_RECURSIVE = PTHREAD_MUTEX_RECURSIVE_NP
        PTHREAD_MUTEX_ERRORCHECK = PTHREAD_MUTEX_ERRORCHECK_NP
        PTHREAD_MUTEX_DEFAULT = PTHREAD_MUTEX_TIMED_NP
        PTHREAD_MUTEX_FAST_NP = PTHREAD_MUTEX_TIMED_NP
        TD_REAP = TD_REAP
        _bitindex_arch_Avoid_Non_Temporal_Memset = _bitindex_arch_Avoid_Non_Temporal_Memset
        DL_LOOKUP_RETURN_NEWEST = DL_LOOKUP_RETURN_NEWEST
        _URC_HANDLER_FOUND = _URC_HANDLER_FOUND
        cpuid_register_index_ecx = cpuid_register_index_ecx
        _bitindex_arch_Avoid_Short_Distance_REP_MOVSB = _bitindex_arch_Avoid_Short_Distance_REP_MOVSB
        _bitindex_arch_Prefer_FSRM = _bitindex_arch_Prefer_FSRM
        lc_property_unknown = lc_property_unknown
        _bitindex_arch_Fast_Unaligned_Load = _bitindex_arch_Fast_Unaligned_Load
        lt_library = lt_library
        cpuid_register_index_edx = cpuid_register_index_edx
        rtld_mode_list_diagnostics = rtld_mode_list_diagnostics
        start_time = 1094493603614
        _URC_NO_REASON = _URC_NO_REASON
        _bitindex_arch_Prefer_PMINUB_for_stringop = _bitindex_arch_Prefer_PMINUB_for_stringop
        plt_rewrite_jmpabs = plt_rewrite_jmpabs
        arch_kind_other = arch_kind_other
        rtld_mode_list = rtld_mode_list
        _dl_rtld_libname = {name = 0x10002e0 "/lib64/ld-linux-x86-64.so.2", next = 0x7a5828648220 <newname>, dont_free = 0}
        TD_IDLE = TD_IDLE
        unknown = unknown
        _URC_FATAL_PHASE2_ERROR = _URC_FATAL_PHASE2_ERROR
        cet_elf_property = cet_elf_property
        RT_ADD = RT_ADD
        _bitindex_arch_Fast_Rep_String = _bitindex_arch_Fast_Rep_String
        _bitindex_arch_MathVec_Prefer_No_AVX512 = _bitindex_arch_MathVec_Prefer_No_AVX512
        _bitindex_arch_Fast_Copy_Backward = _bitindex_arch_Fast_Copy_Backward
        _bitindex_arch_AVX_Fast_Unaligned_Load = _bitindex_arch_AVX_Fast_Unaligned_Load
        existing = existing
        _URC_NORMAL_STOP = _URC_NORMAL_STOP
        lc_property_none = lc_property_none
        nonexisting = nonexisting
        load_time = 8514090
        TD_PREEMPT = TD_PREEMPT
        TD_TIMEOUT = TD_TIMEOUT
        TD_ALL_EVENTS = TD_ALL_EVENTS
        _URC_END_OF_STACK = _URC_END_OF_STACK
        _bitindex_arch_Prefer_No_AVX512 = _bitindex_arch_Prefer_No_AVX512
        arch_kind_intel = arch_kind_intel
        rtld_mode_trace = rtld_mode_trace
        rtld_mode_list_tunables = rtld_mode_list_tunables
        _bitindex_arch_Prefer_ERMS = _bitindex_arch_Prefer_ERMS
        cet_always_on = cet_always_on
        dso_sort_algorithm_dfs = dso_sort_algorithm_dfs
        LA_ACT_DELETE = LA_ACT_DELETE
        TD_SWITCHTO = TD_SWITCHTO
        cet_always_off = cet_always_off
        _bitindex_arch_Slow_BSF = _bitindex_arch_Slow_BSF
        arch_kind_zhaoxin = arch_kind_zhaoxin
        arch_kind_amd = arch_kind_amd
        _URC_FOREIGN_EXCEPTION_CAUGHT = _URC_FOREIGN_EXCEPTION_CAUGHT
        _bitindex_arch_Prefer_No_VZEROUPPER = _bitindex_arch_Prefer_No_VZEROUPPER
        TD_EVENT_NONE = TD_ALL_EVENTS
        TD_EVENTS_ENABLE = TD_EVENTS_ENABLE
        rtld_mode_normal = rtld_mode_normal
        TD_MIN_EVENT_NUM = TD_READY
        lc_property_valid = lc_property_valid
        LA_ACT_ADD = LA_ACT_ADD
        TD_PRI_INHERIT = TD_PRI_INHERIT
        _bitindex_arch_Fast_Unaligned_Copy = _bitindex_arch_Fast_Unaligned_Copy
        _URC_CONTINUE_UNWIND = _URC_CONTINUE_UNWIND
        DL_LOOKUP_FOR_RELOCATE = DL_LOOKUP_FOR_RELOCATE
        lt_loaded = lt_loaded
        plt_rewrite_none = plt_rewrite_none
        DL_LOOKUP_GSCOPE_LOCK = DL_LOOKUP_GSCOPE_LOCK
        _dl_rtld_libname2 = {name = 0x0, next = 0x0, dont_free = 0}
        _bitindex_arch_I586 = _bitindex_arch_I586
        __GI__dl_argv = 0x7fff3dca6c48
        _rtld_global_ro = {_dl_debug_mask = 0, _dl_platform = 0x7fff3dca6ec9 "x86_64", _dl_platformlen = 6, _dl_pagesize = 4096, _dl_minsigstacksize = 1776, _dl_inhibit_cache = 0, _dl_initial_searchlist = {r_list = 0x7a581cf45330, r_nlist = 71}, _dl_clktck = 100, _dl_verbose = 0, _dl_debug_fd = 2, _dl_lazy = 1, _dl_bind_not = 0, _dl_dynamic_weak = 0, _dl_fpu_control = 895, _dl_hwcap = 2, _dl_auxv = 0x7fff3dca6d48, _dl_x86_cpu_features = {basic = {kind = arch_kind_amd, max_cpuid = 16, family = 23, model = 113, stepping = 0}, features = {{{cpuid_array = {8851216, 135006208, 2128097803, 395049983}, cpuid = {eax = 8851216, ebx = 135006208, ecx = 2128097803, edx = 395049983}}, {active_array = {0, 0, 2128097795, 394821904}, active = {eax = 0, ebx = 0, ecx = 2128097795, edx = 394821904}}}, {{cpuid_array = {0, 563909033, 4194308, 0}, cpuid = {eax = 0, ebx = 563909033, ecx = 4194308, edx = 0}}, {active_array = {0, 562823465, 4194304, 0}, active = {eax = 0, ebx = 562823465, ecx = 4194304, edx = 0}}}, {{cpuid_array = {8851216, 536870912, 1975662591, 802421759}, cpuid = {eax = 8851216, ebx = 536870912, ecx = 1975662591, edx = 802421759}}, {active_array = {0, 0, 353, 134217728}, active = {eax = 0, ebx = 0, ecx = 353, edx = 134217728}}}, {{cpuid_array = {15, 832, 0, 0}, cpuid = {eax = 15, ebx = 832, ecx = 0, edx = 0}}, {active_array = {7, 0, 0, 0}, active = {eax = 7, ebx = 0, ecx = 0, edx = 0}}}, {{cpuid_array = {0, 27, 0, 26521}, cpuid = {eax = 0, ebx = 27, ecx = 0, edx = 26521}}, {active_array = {0, 0, 0, 0}, active = {eax = 0, ebx = 0, ecx = 0, edx = 0}}}, {{cpuid_array = {12336, 17610327, 28683, 65536}, cpuid = {eax = 12336, ebx = 17610327, ecx = 28683, edx = 65536}}, {active_array = {0, 512, 0, 0}, active = {eax = 0, ebx = 512, ecx = 0, edx = 0}}}, {{cpuid_array = {0, 0, 0, 0}, cpuid = {eax = 0, ebx = 0, ecx = 0, edx = 0}}, {active_array = {0, 0, 0, 0}, active = {eax = 0, ebx = 0, ecx = 0, edx = 0}}}, {{cpuid_array = {0, 0, 0, 0}, cpuid = {eax = 0, ebx = 0, ecx = 0, edx = 0}}, {active_array = {0, 0, 0, 0}, active = {eax = 0, ebx = 0, ecx = 0, edx = 0}}}, {{cpuid_array = {0, 0, 0, 0}, cpuid = {eax = 0, ebx = 0, ecx = 0, edx = 0}}, {active_array = {0, 0, 0, 0}, active = {eax = 0, ebx = 0, ecx = 0, edx = 0}}}, {{cpuid_array = {0, 0, 0, 0}, cpuid = {eax = 0, ebx = 0, ecx = 0, edx = 0}}, {active_array = {0, 0, 0, 0}, active = {eax = 0, ebx = 0, ecx = 0, edx = 0}}}}, preferred = {704}, isa_1 = 7, xsave_state_size = 960, xsave_state_full_size = 960, data_cache_size = 32768, shared_cache_size = 16777216, non_temporal_threshold = 12582912, memset_non_temporal_threshold = 12582912, rep_movsb_threshold = 12582912, rep_movsb_stop_threshold = 12582912, rep_stosb_threshold = 18446744073709551615, level1_icache_size = 32768, level1_icache_linesize = 64, level1_dcache_size = 32768, level1_dcache_assoc = 8, level1_dcache_linesize = 64, level2_cache_size = 524288, level2_cache_assoc = 8, level2_cache_linesize = 64, level3_cache_size = 16777216, level3_cache_assoc = 16, level3_cache_linesize = 64, level4_cache_size = 0, cachesize_non_temporal_divisor = 4}, _dl_x86_hwcap_flags = {"sse2\000\000\000\000", "x86_64\000\000", "avx512_1"}, _dl_x86_tlsdesc_dynamic = 0x7a5828625b60 <_dl_tlsdesc_dynamic_xsavec>, _dl_x86_64_runtime_resolve = 0x7a5828623660 <_dl_runtime_resolve_xsavec>, _dl_inhibit_rpath = 0x0, _dl_origin_path = 0x0, _dl_tls_static_size = 4992, _dl_tls_static_align = 64, _dl_tls_static_surplus = 1664, _dl_profile = 0x0, _dl_profile_output = 0x7a582863de3e "/var/tmp", _dl_init_all_dirs = 0x7a5828648f30, _dl_sysinfo_dso = 0x7a582860f000, _dl_sysinfo_map = 0x7a58286488c0, _dl_vdso_clock_gettime64 = 0x7a582860fda0 <clock_gettime>, _dl_vdso_gettimeofday = 0x7a582860fa80 <gettimeofday>, _dl_vdso_time = 0x7a582860fd70 <time>, _dl_vdso_getcpu = 0x7a58286101c0 <getcpu>, _dl_vdso_clock_getres_time64 = 0x7a5828610150 <clock_getres>, _dl_hwcap2 = 2, _dl_hwcap3 = 0, _dl_hwcap4 = 0, _dl_dso_sort_algo = dso_sort_algorithm_dfs, _dl_debug_printf = 0x7a582861e010 <_dl_debug_printf>, _dl_mcount = 0x7a582862c640 <__GI__dl_mcount>, _dl_lookup_symbol_x = 0x7a582861a970 <_dl_lookup_symbol_x>, _dl_open = 0x7a582861c850 <_dl_open>, _dl_close = 0x7a5828613640 <_dl_close>, _dl_catch_error = 0x7a5828612650 <_dl_catch_error>, _dl_error_free = 0x7a5828614a60 <_dl_error_free>, _dl_tls_get_addr_soft = 0x7a5828622e40 <_dl_tls_get_addr_soft>, _dl_libc_freeres = 0x7a582862b790 <__rtld_libc_freeres>, _dl_find_object = 0x7a5828634020 <__GI___dl_find_object>, _dl_dlfcn_hook = 0x0, _dl_audit = 0x0, _dl_naudit = 0}
        _dl_argc = 1
        __rtld_tls_init_tp_called = true
        __pointer_chk_guard_local = 4136676215174994886
        _rtld_global = {_dl_ns = {{_ns_loaded = 0x7a58286482e0, _ns_nloaded = 72, _ns_main_searchlist = 0x7a58286485d8, _ns_global_scope_alloc = 0, _ns_global_scope_pending_adds = 0, libc_map = 0x7a5828361000, _ns_unique_sym_table = {lock = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 22 times>, __align = 0}}, entries = 0x7a581ceff000, size = 509, n_elements = 253, free = 0x7a582861b9f0 <__minimal_free>}, _ns_debug = {base = {r_version = 0, r_map = 0x0, r_brk = 0, r_state = RT_CONSISTENT, r_ldbase = 0}, r_next = 0x0}}, {_ns_loaded = 0x0, _ns_nloaded = 0, _ns_main_searchlist = 0x0, _ns_global_scope_alloc = 0, _ns_global_scope_pending_adds = 0, libc_map = 0x0, _ns_unique_sym_table = {lock = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, entries = 0x0, size = 0, n_elements = 0, free = 0x0}, _ns_debug = {base = {r_version = 0, r_map = 0x0, r_brk = 0, r_state = RT_CONSISTENT, r_ldbase = 0}, r_next = 0x0}} <repeats 15 times>}, _dl_nns = 1, _dl_load_lock = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 22 times>, __align = 0}}, _dl_load_write_lock = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 22 times>, __align = 0}}, _dl_load_tls_lock = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 22 times>, __align = 0}}, _dl_load_adds = 72, _dl_initfirst = 0x0, _dl_profile_map = 0x0, _dl_num_relocations = 22296, _dl_num_cache_relocations = 15143, _dl_all_dirs = 0x7a5828648f30, _dl_rtld_map = {l_addr = 134519053160448, l_name = 0x10002e0 "/lib64/ld-linux-x86-64.so.2", l_ld = 0x7a5828646e80, l_next = 0x7a5827dd7000, l_prev = 0x7a5827e044c0, l_real = 0x7a5828647ab0 <_rtld_global+2736>, l_ns = 0, l_libname = 0x7a5828648260 <_dl_rtld_libname>, l_info = {0x0, 0x0, 0x0, 0x0, 0x0, 0x7a5828646ea0, 0x7a5828646eb0, 0x7a5828646ee0, 0x7a5828646ef0, 0x7a5828646f00, 0x7a5828646ec0, 0x7a5828646ed0, 0x0, 0x0, 0x7a5828646e80, 0x0 <repeats 15 times>, 0x7a5828646f30, 0x0, 0x0, 0x0, 0x0, 0x7a5828646f70, 0x7a5828646f60, 0x7a5828646f80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7a5828646f20, 0x7a5828646f10, 0x7a5828646f40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7a5828646f50, 0x0 <repeats 25 times>, 0x7a5828646e90}, l_phdr = 0x7a5828611040, l_entry = 0, l_phnum = 11, l_ldnum = 0, l_searchlist = {r_list = 0x0, r_nlist = 0}, l_symbolic_searchlist = {r_list = 0x0, r_nlist = 0}, l_loader = 0x0, l_versions = 0x7a581cf0d3b0, l_nversions = 8, l_nbuckets = 71, l_gnu_bitmask_idxbits = 3, l_gnu_shift = 8, l_gnu_bitmask = 0x7a5828611320, {l_gnu_buckets = 0x7a5828611340, l_chain = 0x7a5828611340}, {l_gnu_chain_zero = 0x7a5828611458, l_buckets = 0x7a5828611458}, l_direct_opencount = 0, l_type = lt_library, l_dt_relr_ref = 0, l_relocated = 1, l_init_called = 1, l_global = 1, l_reserved = 0, l_main_map = 0, l_visited = 1, l_map_used = 0, l_map_done = 0, l_phdr_allocated = 0, l_soname_added = 0, l_faked = 0, l_need_tls_init = 0, l_auditing = 0, l_audit_any_plt = 0, l_removed = 0, l_contiguous = 0, l_free_initfini = 0, l_ld_readonly = 0, l_find_object_processed = 0, l_nodelete_active = false, l_nodelete_pending = false, l_has_jump_slot_reloc = false, l_property = lc_property_unknown, l_x86_feature_1_and = 0, l_x86_isa_1_needed = 0, l_1_needed = 0, l_rpath_dirs = {dirs = 0x0, malloced = 0}, l_reloc_result = 0x0, l_versyms = 0x7a5828611b82, l_origin = 0x0, l_map_start = 134519053160448, l_map_end = 134519053386464, l_scope_mem = {0x0, 0x0, 0x0, 0x0}, l_scope_max = 0, l_scope = 0x0, l_local_scope = {0x0, 0x0}, l_file_id = {dev = 0, ino = 0}, l_runpath_dirs = {dirs = 0x0, malloced = 0}, l_initfini = 0x0, l_reldeps = 0x0, l_reldepsmax = 0, l_used = 1, l_feature_1 = 0, l_flags_1 = 0, l_flags = 0, l_idx = 0, l_mach = {plt = 0, gotplt = 0, tlsdesc_table = 0x0}, l_lookup_cache = {sym = 0x0, type_class = 0, value = 0x0, ret = 0x0}, l_tls_initimage = 0x0, l_tls_initimage_size = 0, l_tls_blocksize = 0, l_tls_align = 0, l_tls_firstbyte_offset = 0, l_tls_offset = 0, l_tls_modid = 0, l_tls_dtor_count = 0, l_relro_addr = 213728, l_relro_size = 7456, l_serial = 0}, _dl_rtld_auditstate = {{cookie = 0, bindflags = 0} <repeats 16 times>}, _dl_x86_feature_1 = 0, _dl_x86_feature_control = {ibt = cet_elf_property, shstk = cet_elf_property, plt_rewrite = plt_rewrite_none}, _dl_stack_flags = 6, _dl_tls_dtv_gaps = false, _dl_tls_max_dtv_idx = 12, _dl_tls_dtv_slotinfo_list = 0x7a581cf09230, _dl_tls_static_nelem = 12, _dl_tls_static_used = 936, _dl_tls_static_optional = 512, _dl_initial_dtv = 0x7a581cf0aad0, _dl_tls_generation = 1, _dl_scope_free_list = 0x0, _dl_stack_used = {next = 0x7a58286480b8 <_rtld_global+4280>, prev = 0x7a58286480b8 <_rtld_global+4280>}, _dl_stack_user = {next = 0x7a581cf0a400, prev = 0x7a581cf0a400}, _dl_stack_cache = {next = 0x7a58286480d8 <_rtld_global+4312>, prev = 0x7a58286480d8 <_rtld_global+4312>}, _dl_stack_cache_actsize = 0, _dl_in_flight_stack = 0, _dl_stack_cache_lock = 0}
#13 0x0000000000000001 in ?? ()
No symbol table info available.
#14 0x00007fff3dca7c0a in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.
[?2004h(gdb) c
[?2004l
[?2004h(gdb) cexit
[?2004l
[?2004h(gdb) exit
[?2004l
```

**Comment by xiota** [comment]
Package has been updated and rebuilt.  Please let me know if that fixes the problem.

**Comment by 0nobody0** [comment]
thanks, that fixed it.
