### ISSUE TITLE
Kawaii-Player

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#378]
https://aur.archlinux.org/packages/kawaii-player

**Comment by Bhooty** [comment]
optional dependency missing
http://aur.archlinux.org/packages/python-pympv

**Comment by dr460nf1r3** [comment]
Well, gotta mention this too since its not getting pulled automatically :D done

**Comment by Bhooty** [comment]
> Well, gotta mention this too since its not getting pulled automatically :D done

sry found out when tried to install :(

**Comment by xiota** [comment]
Dropping `python-pympv` because it's been unbuildable for at least a month.  It's also optional and not used by anything else.

**Comment by Technetium1** [comment]
@eclairevoyant do you have any plans to fix [python-pympv](https://github.com/eclairevoyant/aur-packages/tree/main/python-pympv) / [python-pympv-git](https://github.com/eclairevoyant/aur-packages/tree/main/python-pympv-git) soon? Should we open an issue on your repo? Your inputs are appreciated.

**Comment by xiota** [comment]
May have to drop `kawaii-player` too.  Builds successfully, but fails to run.  Unable to test `kawaii-player-git` because it's currently unbuildable.  Missing/broken depends.
```
/usr/lib/python3.11/site-packages/kawaii_player kawaii_player.py /tmp
['/usr/lib/python3.11/site-packages/kawaii_player', '/usr/bin', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/site-packages', '/usr/lib/python3.11/site-packages/linkgrammar']
--using default pycurl--
Traceback (most recent call last):
  File "/usr/bin/kawaii-player", line 33, in <module>
    sys.exit(load_entry_point('kawaii-player==5.0.0', 'gui_scripts', 'kawaii-player')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/kawaii-player", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/kawaii_player/kawaii_player.py", line 93, in <module>
    from guisignals import GUISignals
  File "/usr/lib/python3.11/site-packages/kawaii_player/guisignals.py", line 27, in <module>
    from settings_widget import LoginPCToPC
  File "/usr/lib/python3.11/site-packages/kawaii_player/settings_widget.py", line 32, in <module>
    from widgets.optionwidgets import QPushButtonExtra
  File "/usr/lib/python3.11/site-packages/kawaii_player/widgets/optionwidgets.py", line 16, in <module>
    from mpv_bak import MPV
  File "/usr/lib/python3.11/site-packages/kawaii_player/mpv_bak.py", line 409, in <module>
    _handle_func('mpv_detach_destroy',          [],                                         None, errcheck=None)
  File "/usr/lib/python3.11/site-packages/kawaii_player/mpv_bak.py", line 366, in _handle_func
    func = getattr(backend, name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: /usr/lib/libmpv.so.2: undefined symbol: mpv_detach_destroy
```
