### ISSUE TITLE
[Request] Ryujinx (Switch Emulator)

### ISSUE THREAD

**Issue by NerosTie** [chaotic-aur/packages#558]
Git: https://github.com/Ryujinx/Ryujinx
AUR: https://aur.archlinux.org/packages/ryujinx-git/
https://ryujinx.org/

**Comment by NerosTie** [comment]
There is an error when launching Ryujinx:

```
00:00:00.376 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in /home/main-builder/pkgwork/src/Ryujinx/Ryujinx/Ui/MainWindow.cs:line 129
   at Ryujinx.Program.Main(String[] args) in /home/main-builder/pkgwork/src/Ryujinx/Ryujinx/Program.cs:line 165
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in /home/main-builder/pkgwork/src/Ryujinx/Ryujinx/Ui/MainWindow.cs:line 129
   at Ryujinx.Program.Main(String[] args) in /home/main-builder/pkgwork/src/Ryujinx/Ryujinx/Program.cs:line 165
[1]    9592 abort (core dumped)  Ryujinx

```

I guess that `main-builder` is the name of your home folder.

**Comment by NerosTie** [comment]
Never mind, it crashes on Wayland but not on X11 and it is probably normal.
