### ISSUE TITLE
Signal-Desktop-Beta crashes upon startup because of missing CXX runtime environment

### ISSUE THREAD

**Issue by major-mayer** [chaotic-aur/packages#638]
Since a few days when I try to open up Signal-Desktop-Beta it crashes with this error message:
``` 
~ >>> signal-desktop-beta                                                      
NODE_ENV production
NODE_CONFIG_DIR /usr/lib/signal-desktop-beta/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/laurenz/.config/Signal Beta
config/get: Successfully read user config file
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop-beta' }
x-attr dependency did not load successfully
config/get: Successfully read ephemeral config file
making app single instance
Unhandled Error: Error: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/signal-desktop-beta/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Function.Module._load (internal/modules/cjs/loader.js:776:14)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.better_sqlite3.node (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:31506:18)
    at __webpack_require__ (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:31607:42)
    at module.exports (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:31155:16)
    at Object../node_modules/better-sqlite3/lib/database.js (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:432:74)
    at __webpack_require__ (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:31607:42)
Unhandled Error: Error: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/signal-desktop-beta/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Function.Module._load (internal/modules/cjs/loader.js:776:14)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.better_sqlite3.node (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:31506:18)
    at __webpack_require__ (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:31607:42)
    at module.exports (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:31155:16)
    at Object../node_modules/better-sqlite3/lib/database.js (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:432:74)
    at __webpack_require__ (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:31607:42)
Unhandled Error
Error: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/signal-desktop-beta/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Function.Module._load (internal/modules/cjs/loader.js:776:14)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.better_sqlite3.node (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:31506:18)
    at __webpack_require__ (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:31607:42)
    at module.exports (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:31155:16)
    at Object../node_modules/better-sqlite3/lib/database.js (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:432:74)
    at __webpack_require__ (/usr/lib/signal-desktop-beta/resources/app.asar.unpacked/ts/sql/mainWorker.bundle.js:31607:42)
``` 
I am using Manjaro Linux, installed the package via Pamac.
It worked great before, but now it's complaining that "GLIBCXX_3.4.29" is not find. 
"GLIBCXX_3.4.29" would correspond to GCC 11, which is pretty new and Manjaro Linux doesn't support it.

Signal-desktop-beta-bin does work, so I guess this can be fixed too.

**Comment by dr460nf1r3** [comment]
Chaotic-AUR is primarily for Arch, so packages are compiled against Arch package versions rather than Manjaro ones.

**Comment by major-mayer** [comment]
Ahh okay, didn't know about this. 
Thanks for the explanation!
